### ISSUE TITLE
Issue with running plot_end_dists

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TALON-paper-2020#2]
python version 3.6.7, also tried python 3.7.2. Tried using comma separate list of datasets in the terminal and a list .CSV file.

```
python TALON-paper-2020/end_analysis/plot_end_dists.py -f Mouse_aging/TALON/TALON_dRNA_mm10_talon_read_annot_mod.tsv -a Genome_files/Mus_musculus.GRCm38.99_TSS_and_TES.tsv --datasets Mouse_aging/TALON/whitelist/samples.csv -xlim 8000 -ylim 5000 -o Mouse_aging/TALON/plots/end_analysis/TALON_dRNA_mm10
```
Error ouput
```
sys:1: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "TALON-paper-2020/plotting_scripts/plot_read_length_by_novelty.py", line 131, in <module>
    main()
  File "TALON-paper-2020/plotting_scripts/plot_read_length_by_novelty.py", line 114, in main
    data = data[~filter]
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1324, in __invert__
    new_data = self._mgr.apply(operator.invert)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 407, in apply
    applied = b.apply(f, **kwargs)
  File "/home/callum/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 346, in apply
    result = func(self.values, **kwargs)
TypeError: bad operand type for unary ~: 'float'
```

head of input files:

annot_file
```
read_name	dataset	genome_build	chrom	read_start	read_end	strand	n_exons	read_length	gene_ID	transcript_ID	annot_gene_id	annot_transcript_id	annot_gene_name	annot_transcript_name	gene_novelty	transcript_novelty	ISM_subtype	fraction_As	custom_label	allelic_label	start_support	end_support
6eebcb2a-b5d1-40da-b409-35990366af14	M_GF_old_rep1	mus_musculus_99	16	3292339	3292512	+	1	174	55472	142648	TALONG000055472	TALONT000142648	TALONG000055472	TALONT000142648	Intergenic	Intergenic	None	0.44999998807907104	None	None	None	None
064b1390-57ba-40d4-a9a9-ee64906f7d6c	F_SPF_old_rep4	mus_musculus_99	12	3063154	3063323	+	1	170	55473	142649	TALONG000055473	TALONT000142649	TALONG000055473	TALONT000142649	Intergenic	Intergenic	None	0.20000000298023224	None	None	None	None
eb461894-cf1a-4942-a333-8287b8321cfe	F_GF_old_rep4	mus_musculus_99	17	3044756	3043851	-	2	751	48667	142650	ENSMUSG00000068141	TALONT000142650	Gm10232	TALONT000142650	Known	Genomic	None	0.25	None	None	None	None
8560943d-d013-47fd-906a-5aacbf0824fa	F_SPF_young_rep5	mus_musculus_99	19	3033983	3034426	+	1	444	55474	142651	TALONG000055474	TALONT000142651	TALONG000055474	TALONT000142651	Intergenic	IntergeniNone	0.3499999940395355	None	None	None	None
e4ffa640-7b20-40e3-8c04-0a8c311264f0	M_SPF_young_rep3	mus_musculus_99	14	3049085	3076842	+	7	2182	31859	81816	ENSMUSG00000079410	ENSMUST00000166494	Gm2897	Gm2897-201	Known	Known	None	0.15000000596046448	None	None	None	None
e1830ba0-c4a9-4ea5-a744-0f8758683071	M_SPF_young_rep2	mus_musculus_99	6	3185494	3184697	-	1	798	55475	142652	TALONG000055475	TALONT000142652	TALONG000055475	TALONT000142652	Intergenic	IntergeniNone	0.0	None	None	None	None
2655636e-1a07-453d-8902-1f233593d20d	F_GF_old_rep4	mus_musculus_99	17	3044254	3043852	-	1	390	48667	125223	ENSMUSG00000068141	ENSMUST00000089221	Gm10232	Gm10232-201	Known	Known	None	0.30000001192092896	None	None	None	None
23d152b9-9020-4182-aead-47bf81d15779	M_GF_old_rep3	mus_musculus_99	17	3044748	3043858	-	1	891	48667	125223	ENSMUSG00000068141	ENSMUST00000089221	Gm10232	Gm10232-201	Known	Known	None	0.44999998807907104	None	None	None	None
d48ab7dd-4440-4f17-aa74-bc0dd44c2977	M_GF_old_rep4	mus_musculus_99	13	3100107	3096030	-	1	4070	55476	142653	TALONG000055476	TALONT000142653	TALONG000055476	TALONT000142653	Antisense	Antisense	None	0.05000000074505806	None	None	None	None
```

ends annotations

```
annot_transcript_id     TSS_pos TES_pos
ENSMUST00000193812      3073253 3074322
ENSMUST00000082908      3102016 3102125
ENSMUST00000162897      3216344 3205901
ENSMUST00000159265      3215632 3206523
ENSMUST00000070533      3671498 3214482
ENSMUST00000192857      3252757 3253236
ENSMUST00000195335      3368549 3365731
ENSMUST00000192336      3377788 3375556
ENSMUST00000194099      3467285 3464977
ENSMUST00000161581      3466587 3513553
ENSMUST00000192973      3514507 3512451
ENSMUST00000192183      3531795 3532720
ENSMUST00000195166      3595903 3592892
ENSMUST00000192692      3658904 3647309
ENSMUST00000193244      3680155 3681788
ENSMUST00000194454      3752010 3754360
ENSMUST00000157708      3783933 3783876
ENSMUST00000194643      3986215 3905739
ENSMUST00000192427      3985984 3984225
```

**Comment by fairliereese** [comment]
Hi, 
I think you may have attached the error output from the other problem you were having. It looks the same!

**Comment by callumparr** [comment]
Ah sorry for the confusion. I was getting this error, the same as the other issue and then I changed the similar lines that use the `contains()` to include `na = False`. But now I get a similar error as I do when I run this script on the example data in TALON-5.0. It seems to pass over the dataframe with no issues but is some issue when saving the plots to file as they are empty.

I googled and something to do with the `plt()`. I've tried some solutions like here https://stackoverflow.com/questions/62084819/exception-in-tkinter-callback-using-shap but none seem to work.

```
sys:1: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
Saving plot Mouse_aging/TALON/plots/end_analysis/M_SPF_old_tss_dists_hires.png
Saving plot Mouse_aging/TALON/plots/end_analysis/M_SPF_old_tes_dists_hires.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7ff150f5f390>
Saving plot Mouse_aging/TALON/plots/end_analysis/M_SPF_old_tss_dists.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7ff1ba418b38>
Saving plot Mouse_aging/TALON/plots/end_analysis/M_SPF_old_tes_dists.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7ff137dd6e48>
```

If I try on the example data:

```
python $HOME/TALON-paper-2020/end_analysis/plot_end_dists.py -f example_talon_read_annot.tsv -a SIRV --datasets SIRV_Rep1,SIR_Rep2 -xlim 800 -ylim 90000 -o pb
```

Gives same error:

```
Saving plot pb_tss_dists_hires.png
Saving plot pb_tes_dists_hires.png
Saving plot pb_tss_dists.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7fa5a8fb3470>
Saving plot pb_tes_dists.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/callum/miniconda3/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/callum/miniconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7fa5a5e81be0>
```

**Comment by fairliereese** [comment]
I'm not sure what's going on... Looks like your issue is with a library called "tkinter" which after some googling is a GUI library, but that library is never used in this repository. Are you running this on a cluster? Sometimes there is weird behavior when the script wants to render a plot on the cluster because there is no graphics interface to output it to. I'd recommend making a new python environment possibly without tkinter and seeing if you can run it again.

**Comment by callumparr** [comment]
Ah OK that makes sense yes am running on our server although there is xforwarding enabled when SSH login. It would be better to try without tkinter. 

This works after activating another python environment wihout tkinter.

Thank you for your help
